[package]
name = "art-of-rally-leaderboard-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
comfy-table = { version = "7.1.4", default-features = false }
curl = "0.4.47"
itertools = "0.14.0"
serde = "1.0.217"
serde_json = "1.0.138"

[dependencies.art-of-rally-leaderboard-api]
git = "https://github.com/sornas/art-of-rally-leaderboard-api"
branch = "enum-iter"
version = "0.1.0"
features = ["enum-iter"]
